---
# Host variable file for Leaf1

features:
  - ospf
  - bgp
  - vn-segment-vlan-based
  - nv overlay
  - fabric forwarding
  - interface-vlan
  - scp-server

mgmt_ip: 192.168.1.202
mgmt_mask: 24
mgmt_gateway: 192.168.1.1

anycast_gateway_mac: aabb.cc01.1122

l3_interfaces:
  - { interface: Ethernet1/1, description: LINK_TO_SPINE1 }
  - { interface: Ethernet1/2, description: LINK_TO_SPINE2 }

l2_interfaces:
  - { interface: Ethernet1/3, description: LINK_TO_R1, mode: trunk, allowed_vlans: "100,200,300" }
  #- { interface: Ethernet1/4, description: LINK_TO_R4, mode: access, vlan: "100" }

loopbacks:
  - { interface: loopback0, description: UNDERLAY_LOOPBACK, ip_addr: 172.32.32.3/32 }
  - { interface: loopback1, description: OVERLAY_LOOPBACK, ip_addr: 172.62.62.3/32 }
  - { interface: loopback2, description: VTEP_LOOPBACK, ip_addr: 172.92.92.3/32 }

vtep:
  interface: nve1
  description: VTEP_INTERFACE 
  reachability: bgp
  source_int: loopback2
  member_vni:
    - { vni_id: 200100, ingress_rep: bgp }
    - { vni_id: 200200, ingress_rep: bgp }
    - { vni_id: 200300, ingress_rep: bgp }
  member_vni_vrf:
    - vni_id: 500001 
    - vni_id: 500002 

ospf_process_id: UNDERLAY
ospf_router_id: "172.32.32.3"
ospf_area: "0.0.0.0"

bgp_asn: "65513"
bgp_router_id: "172.62.62.3"

address_families:
  - { afi: l2vpn, safi: evpn }
  - { afi: ipv4, safi: unicast }

bgp_neighbors:
  - { neighbor: "172.62.62.1", remote_as: "65513", description: SPINE1-PEER, update_source: loopback1 }
  - { neighbor: "172.62.62.2", remote_as: "65513", description: SPINE2-PEER, update_source: loopback1 }

vlans:
  - { vlan_id: 100, vlan_name: Accounting, vni_id: 200100, ip_addr: 10.100.1.1/24, tag: 500001, vrf: TENANT-A }
  - { vlan_id: 200, vlan_name: Sales, vni_id: 200200, ip_addr: 10.200.1.1/24, tag: 500002, vrf: TENANT-B }
  - { vlan_id: 300, vlan_name: Engineering, vni_id: 200300, ip_addr: 10.250.1.1/24, tag: 500001, vrf: TENANT-A }
  - { vlan_id: 3000, vlan_name: VXLAN-SVI-VLAN-TENANT-A, vni_id: 500001, vrf: TENANT-A }
  - { vlan_id: 3001, vlan_name: VXLAN-SVI-VLAN-TENANT-B, vni_id: 500002, vrf: TENANT-B }

vrfs:
  - { vrf: TENANT-A, vni_id: 500001, afi: ipv4, safi: unicast, route_map: RM-TENANT-A-ROUTES }
  - { vrf: TENANT-B, vni_id: 500002, afi: ipv4, safi: unicast, route_map: RM-TENANT-B-ROUTES }

...